name: Issue assigment

on: 
  issues:
    types: [opened]
    
jobs:
  auto-assign:
    runs-on: ubuntu-lates
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: qinkeith
